#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2012-2022 OKTET Labs Ltd.

export TE_IUT_TA_NAME="IUT"
export TE_TST1_TA_NAME="Peer"
export TE_LOG_LISTENER_TA_NAME="LogListener"
export TE_TA_SIGNATURE_FIELDS="gcc-target kernel-version-full libc-version header-version"

if test -z "${TE_LOG_LISTENER}" -a -n "${TE_TST3}" ; then
    # TE_TST3 is an alternative name of the log listener.
    export TE_LOG_LISTENER=${TE_TST3}
    export TE_LOG_LISTENER_NETCONSOLE_IUT=yes
    export TE_LOG_LISTENER_NETCONSOLE_TST1=yes
fi

source "${TE_BASE}"/engine/builder/te_ta_ssh_helper

: ${TS_TEST_AGENTS:=TE_IUT TE_TST1 TE_LOG_LISTENER}

te_ta_list_detect_type_with_signature ${TS_TEST_AGENTS}
