#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2012-2022 OKTET Labs Ltd.
#
# Helper script to generate test suite documentation.
#

set -e

export TS_TOPDIR="$(cd "$(dirname "$(which "$0")")/.."; pwd -P)"
. ${TS_TOPDIR}/scripts/guess.sh

doxygen_debug=false

help() {
    cat <<EOF
Tool is used to generate documentation for the ibvapi-ts test suite.

It's based on doxygen and doxyrest.

Usage: ./$0 [--help] [--debug]
EOF
}

for opt ; do
    case "${opt}" in
        --help|-h)
            help
            exit 0
            ;;
        -d|--debug)
            doxygen_debug=true
            ;;
        *)
            help
            exit 1
            ;;
    esac
done

if [ -z "$DOXYREST_PREFIX" ]; then
    $TE_BASE/scripts/doxyrest_deploy.sh --how
    exit -1
fi
[ -z "$DOXYREST_BIN" ] && DOXYREST_BIN="$DOXYREST_PREFIX/bin/doxyrest"

[ -z "$SPHINX_BUILD_BIN" ] && SPHINX_BUILD_BIN="sphinx-build"
if ! which $SPHINX_BUILD_BIN >/dev/null; then
    echo "Please install sphinx before:"
    echo " $ pip install sphinx sphinx_rtd_theme"
    exit -2
fi

pushd ${TS_TOPDIR} >/dev/null

if $doxygen_debug ; then
   doxygen -d extcmd -d filteroutput ibvapi-ts/Doxyfile
else
    doxygen ibvapi-ts/Doxyfile >/dev/null
fi

DOXYREST_OPTS=(
    --config=ibvapi-ts/doc/doxyrest-config.lua
    --frame-dir=$DOXYREST_PREFIX/share/doxyrest/frame/cfamily
    --frame-dir=$DOXYREST_PREFIX/share/doxyrest/frame/common
)

${DOXYREST_BIN} "${DOXYREST_OPTS[@]}" || exit 1

SPHINX_BUILD_OPTS=(
    -j auto                     # use cpu count
    -q                          # be quite: warn and error only
    ibvapi-ts/doc                  # input
    ibvapi-ts/doc/generated/html   # output
)

${SPHINX_BUILD_BIN} "${SPHINX_BUILD_OPTS[@]}"
popd >/dev/null
